### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by HaroldChen19** [JeremyCJM/DiffSHEG#1]
Thanks for your awesome work, and when the training code is going to be released?

**Comment by JeremyCJM** [comment]
Hi Harold, the training code is already in this repo. For the dataset processing, I will write a guide later. If you want to try by yourself, you can refer to the official BEAT and TalkSHOW GitHub repo for the data processing. The general process is extracting motion and audio feature clips via sliding window and save them via lmdb.

**Comment by HaroldChen19** [comment]
> Hi Harold, the training code is already in this repo. For the dataset processing, I will write a guide later. If you want to try by yourself, you can refer to the official BEAT and TalkSHOW GitHub repo for the data processing. The general process is extracting motion and audio feature clips via sliding window and save them via lmdb.

Thank you so much!!
