### ISSUE TITLE
 the mouth opens too wide and cannot close

### ISSUE THREAD

**Issue by yangleituitui** [JeremyCJM/DiffSHEG#12]
Hello, I'm working with the BEAT dataset to infer facial expressions and gestures from speech, and after visualizing with Blender, the mouth opens too wide and cannot close. What could be the reason for this issue?
![微信图片_20240609163712](https://github.com/JeremyCJM/DiffSHEG/assets/74516357/a39a7eb1-a09a-48a3-995d-2f574698e6e6)

**Comment by JeremyCJM** [comment]
Hi Yanglei, what is the audio you utilized for inference? If the audio differs a lot with training audios, such issue can happen due to the model generalization ability.

**Comment by yangleituitui** [comment]
Thank you very much for your answer. I have already solved the problem; it was an error with the downloaded voice model. I would also like to ask, where is the facial frame rate originally at 60 FPS converted to 15 FPS

**Comment by JeremyCJM** [comment]
Hi Yanglei, you can downsample the facial sequences to 15 FPS. This is the original setting in the BEAT paper.
