### ISSUE TITLE
MotionAutoencoder checkpoint file

### ISSUE THREAD

**Issue by lovemino** [JeremyCJM/DiffSHEG#13]
Thank you for this awesome work! I encountered the following issues when using this command:
No such file: ges_axis_angle_300.bin
I noticed that the metrics in the experimental results you provided differ from those in Beat. I am wondering if you used different MotionAutoencoder for testing. If so, could you kindly provide the autoencoder checkpoint file? I would greatly appreciate it.

_Originally posted by @lovemino in https://github.com/JeremyCJM/DiffSHEG/issues/2#issuecomment-2161031673_

**Comment by JeremyCJM** [comment]
Hi lovemino, here is the checkpoints link: https://drive.google.com/file/d/1Wm2WMlacwStFaciCh7UlhQeyA3E2yEnj/view?usp=sharing. Those checkpoints are for the autoencoders that compute features for Frechet Distance.
