### ISSUE TITLE
Floating point exception(core dumped)

### ISSUE THREAD

**Issue by XuankeShi** [JeremyCJM/DiffSHEG#15]
i run the inference code by the command "bash inference_custom_audio_beat.sh"
but the code failed in the model forward process
model_output = model(x, self._scale_timesteps(t), **model_kwargs)

**Comment by xungeer29** [comment]
I also have this problem. How to solve it?

**Comment by xungeer29** [comment]
> I also have this problem. How to solve it?

找到问题了，是torch版本与numpy版本的问题，先导入numpy，再导入torch，就会发生这种情况
升级torch版本可以解决
