### ISSUE TITLE
About the number of generated motions and the length of the audio

### ISSUE THREAD

**Issue by Mumuwei** [JeremyCJM/DiffSHEG#16]
Thanks for your work! Some confusion was encountered during testing.

I used the provided audio _Forrest_tts.wav_ and then ran _inference_custom_audio_show.sh_, and I got 1778 frames of motion information. I rendered the generated motion, then I had to set the video fps=15 to match the audio length, which seemed to have a problem.

**Comment by XuankeShi** [comment]
> Thanks for your work! Some confusion was encountered during testing.
> 
> I used the provided audio _Forrest_tts.wav_ and then ran _inference_custom_audio_show.sh_, and I got 1778 frames of motion information. I rendered the generated motion, then I had to set the video fps=15 to match the audio length, which seemed to have a problem.
![image](https://github.com/JeremyCJM/DiffSHEG/assets/40144955/506ca9c4-934a-4ce0-915b-88aa5aee4b5a)
请问下, 你是否遇到过类似的报错

**Comment by Mumuwei** [comment]
@XuankeShi 抱歉，没有遇到过这个问题。

**Comment by XuankeShi** [comment]
> @XuankeShi 抱歉，没有遇到过这个问题。
你使用inference_custom_audio_show.sh这个脚本, 不会出现这个文件路径不存在的问题么?
data/SHOW/cached_data/talkshow_test_cache

**Comment by XuankeShi** [comment]
> @XuankeShi 抱歉，没有遇到过这个问题。

![image](https://github.com/JeremyCJM/DiffSHEG/assets/40144955/5316ef16-fa2e-4b6a-ad9b-34a61cb18f03)

**Comment by Mumuwei** [comment]
@XuankeShi  inference_custom_audio_show.sh 这个脚本我是可以正常运行的，就是生成的帧数和音频对不上，如果按照fps=30的话。如果fps=15能对上，但是渲染出来的视频乖乖的。

**Comment by JeremyCJM** [comment]
That is right. The FPS of BEAT is set to 15 in the processed dataset, following the setting of original BEAT paper.

**Comment by Mumuwei** [comment]
Thanks for your reply. If I want to test the results on SHOW (fps=30) and load the provided pre-trained model on the SHOW dataset, how do I modify the code?
