### ISSUE TITLE
Convert SMPLX Expressions to ARKit Blendshapes for Visualization in Unreal Engine

### ISSUE THREAD

**Issue by SlimeVRX** [JeremyCJM/DiffSHEG#18]
Hi!

The process of visualizing SMPLX in Unreal Engine

https://github.com/JeremyCJM/DiffSHEG/assets/99313947/aa1809ef-f818-4eaa-adb6-d41e3c401f99

I need face data in a format similar to ARKit, but I am unsure how to convert face data from SMPLX to ARKit.

Is there a possible way to convert SMPLX expressions to ARKit blendshapes?

Thank you!

**Comment by JeremyCJM** [comment]
Hi SlimeVRX, thanks for your question. We only did Metahuman visualization in Unreal Engine for results on BEAT dataset. Regarding visualizing SMPLX in Unreal Engine, we have not tried yet.

**Comment by SlimeVRX** [comment]
Hi,

Thank you for your response. I appreciate your clarification regarding the Metahuman visualization in Unreal Engine for the BEAT dataset. It's good to know the scope of your current work.

**Comment by JeremyCJM** [comment]
Thanks for your understanding! I heard that the Blendshape in SMPLX might not be the same as that of ARKit. I am not sure, but you can keep an eye on that:)
