### ISSUE TITLE
Could not find "trump.json"

### ISSUE THREAD

**Issue by arunsandy1309** [JeremyCJM/DiffSHEG#24]
I'm testing this windows laptop, In the blender.py code, I was able to find the change the variable locations for Sound_Name and Movie_Name. But could not find the locations for others 

FACE_ANIM_NAME = r"C:\Users\cjm\OneDrive - HKUST Connect\Documents\0 Research Projects\GestureGeneration\BEAT_Blender_Renderer\rendervideo\trump.json"

SOUND_NAME = r"E:\DiffSHEG\DiffSHEG\audios\2_scott_0_3_3.wav"

MOTION_NAME = r"E:\DiffSHEG\DiffSHEG\assets\data\data\BEAT\beat_cache\beat_4english_15_141\test\bvh_rot_vis\2_scott_0_1_1.bvh"

VIDEO_NAME = r"C:\Users\cjm\OneDrive - HKUST Connect\Documents\0 Research Projects\GestureGeneration\BEAT_Blender_Renderer\rendervideo\trump.mp4"

render_moive(FACE_ANIM_NAME, SOUND_NAME, MOTION_NAME, VIDEO_NAME)

Below is the error that I'm getting once I run this 
![image](https://github.com/user-attachments/assets/468b63c8-7e76-47f0-b9d2-a5bde91f09c6)

**Comment by arunsandy1309** [comment]
I  solved the issue..

**Comment by zc388** [comment]
how do you organize thess datas？i don't even konw how to get it...
it's seems that this project lacks some methods for handling and distributing data.
such as wave16k，axis_angle_mean，axis_angle_std, and mdb for hubert.
![屏幕截图 2024-12-09 203107](https://github.com/user-attachments/assets/80112d32-58b6-4680-8ff2-c9ab966ba209)

**Comment by zc388** [comment]
wait,maybe 'axis_angle_mean' and 'axis_angle_std' are same with the tar.gz file????!
