### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/SHOW/talkshow_mean_std.npy'

### ISSUE THREAD

**Issue by johndpope** [JeremyCJM/DiffSHEG#7]
(diffsheg) ➜  DiffSHEG git:(main) ✗ ./inference_custom_audio_show.sh
------------ Options -------------
ExprID_off: False
ExprID_off_uncond: False
PE: pe_sinu
ablation: None
addBlend: True
addEmoCond: False
addHubert: True
addTextCond: False
addWav2Vec2: False
add_vel_loss: True
audio_dim: 128
audio_feat: mel
audio_latent_dim: 256
axis_angle: True
batch_size: 32
beat_cache_name: beat_4english_15_141
checkpoints_dir: ./checkpoints
ckpt: ckpt_e2599.tar
classifier_free: True
cond_projection: mlp_includeX
cond_residual: True
cond_scale: 1.15
data_mode: original
data_parallel: False
data_root: ./Freeform/processed_data_200
data_sel: upperbody
data_type: pos
dataset_name: talkshow
ddim: True
debug: False
decomp_name: Decomp_SP001_SM001_H512
diffusion_steps: 1000
dim_att_vec: 512
dim_dec_hidden: 1024
dim_movement_dec_hidden: 512
dim_movement_enc_hidden: 512
dim_movement_latent: 512
dim_pos_hidden: 1024
dim_pri_hidden: 1024
dim_text_hidden: 512
dim_z: 128
dist_backend: nccl
dist_url: tcp://224.66.41.62:23456
distributed: False
embed_net_path: feature_extractor/gesture_autoencoder_checkpoint_best.bin
encode_hubert: True
encode_wav2vec2: False
eval_every_e: 5
expAddHubert: False
expCondition_gesture_only: None
expr_weight: 1
expression_only: False
feat_bias: 5
fix_head_var: False
fix_very_first: False
gesCondition_expression_only: False
gesture_only: False
gpu_id: None
is_train: True
jump_length: 3
jump_n_sample: 5
latent_dim: 512
log_every: 50
lr: 0.0002
max_eval_samples: -1
mode: test_custom_audio
model_base: transformer_encoder
model_mean_type: epsilon
multiprocessing_distributed: False
n_layers_dec: 1
n_layers_pos: 1
n_layers_pri: 1
n_poses: 88
name: talkshow_GesExpr_unify_addHubert_encodeHubert_mdlpIncludeX_condRes_LN_ClsFree
no_clip: False
no_eff: False
no_fgd: False
no_repaint: False
no_resample: False
no_style: False
null_cond_prob: 0.2
num_epochs: 5000
num_layers: 8
output_gt: False
overlap_len: 10
rank: 0
rebuttal: None
remove_audio: False
remove_hand: False
remove_style: False
rename: None
reset_lr: False
resume: False
same_overlap_noisy: False
save_every_e: 5
save_latest: 500
separate: None
separate_pure: False
style_dim: 4
test_audio_path: audios/Forrest_tts.wav
test_on_trainset: False
test_on_val: False
textExpEmoCondition_gesture_only: False
times: 1
timestep_respacing: ddim25
unidiffuser: True
usePredExpr: None
use_aud_feat: None
use_joints: False
use_single_style: False
vel_interval: 10
vel_loss_start: -1
visualize_unify_x0_step: None
workers: 0
world_size: 1
-------------- End ----------------
=> creating model 'transformer_encoder'
init 'HalfEmbeddingNet' success
Traceback (most recent call last):
  File "/media/oem/12TB/DiffSHEG/runner.py", line 327, in <module>
    main()
  File "/media/oem/12TB/DiffSHEG/runner.py", line 86, in main
    main_worker(opt.gpu_id, ngpus_per_node, opt)
  File "/media/oem/12TB/DiffSHEG/runner.py", line 312, in main_worker
    test_dataset = ShowDataset(opt, 'data/SHOW/cached_data/talkshow_test_cache')
  File "/media/oem/12TB/DiffSHEG/datasets/show.py", line 43, in __init__
    mean_std_dict = np.load("data/SHOW/talkshow_mean_std.npy", allow_pickle=True)[()]
  File "/home/oem/miniconda3/envs/diffsheg/lib/python3.9/site-packages/numpy/lib/npyio.py", line 427, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'data/SHOW/talkshow_mean_std.npy'

**Comment by johndpope** [comment]
https://talkshow.is.tue.mpg.de/login.php

I downloaded a 16gb file 
16G May 14 17:48 SHOW_dataset_v1.0.zip

but it doesn't include this file...

what's the specific download I need?

**Comment by JeremyCJM** [comment]
Hi, please follow the instructions in README.md.
```
tar zxvf data.tar.gz
mv data ../
```
