### ISSUE TITLE
gesture_expression.pth.tar 

### ISSUE THREAD

**Issue by zhiyoujingtian** [JeremyCJM/DiffSHEG#8]
Could you provide gesture_expression.pth.tar? Thanks

**Comment by JeremyCJM** [comment]
Yes, here is the link: https://drive.google.com/file/d/1Wm2WMlacwStFaciCh7UlhQeyA3E2yEnj/view?usp=sharing. Note that those checkpoints are only for autoencoders that compute features for Frechet Distance.
