### ISSUE TITLE
推理数据用的是音频？

### ISSUE THREAD

**Issue by beibidesr** [JeremyCJM/DiffSHEG#9]
这个任务只能用语音进行推理吗？那为什么 演示的是人在说话呢？应该还要输入一张图片？

**Comment by JeremyCJM** [comment]
对的，这个任务是输入 speech， 输出对应的 expression 和 gesture。这里的expression和gesture只是表示motion的数据（blenshape 和 joint rotation），要得到人物动画，需要用生成的motion来驱动or渲染出你所选择的数字人形象。详情可以参考我们的paper ：）

**Comment by beibidesr** [comment]
谢谢大佬，了解了
